// packages/embed-vue/src/Embed.vue
<script setup lang="ts">
import {
  createEmbed,
  EmbedError,
  EmbedErrorCodes,
  EmbedStatuses,
} from "@codatum/embed";
import type {
  EmbedInstance,
  EmbedStatus,
  DisplayOptions,
  ExecuteSqlsTriggeredMessage,
  IframeOptions,
  ParamChangedMessage,
  TokenOptions,
  TokenProviderContext,
  TokenProviderResult,
} from "@codatum/embed";
import { onMounted, onUnmounted, ref } from "vue";

const props = defineProps<{
  embedUrl: string;
  tokenProvider: (
    context: TokenProviderContext
  ) => Promise<TokenProviderResult>;
  iframeOptions?: IframeOptions;
  tokenOptions?: TokenOptions;
  displayOptions?: DisplayOptions;
}>();

const emit = defineEmits<{
  paramChanged: [payload: ParamChangedMessage];
  executeSqlsTriggered: [payload: ExecuteSqlsTriggeredMessage];
  ready: [];
  error: [err: EmbedError];
}>();

const containerRef = ref<HTMLElement | null>(null);
const instance = ref<EmbedInstance | null>(null);
const status = ref<EmbedStatus>(EmbedStatuses.CREATED);
const error = ref<EmbedError | null>(null);

const toEmbedError = (err: unknown): EmbedError =>
  err instanceof EmbedError
    ? err
    : new EmbedError(
        EmbedErrorCodes.TOKEN_PROVIDER_FAILED,
        err instanceof Error ? err.message : String(err),
        { cause: err }
      );

const setError = (err: unknown) => {
  const embedError = toEmbedError(err);
  error.value = embedError;
  emit("error", embedError);
};

onMounted(async () => {
  const el = containerRef.value;
  if (!el) return;

  const embed = createEmbed({
    container: el,
    embedUrl: props.embedUrl,
    tokenProvider: props.tokenProvider,
    iframeOptions: props.iframeOptions,
    tokenOptions: {
      ...props.tokenOptions,
      onRefreshError: (err: EmbedError) => {
        props.tokenOptions?.onRefreshError?.(err);
        setError(err);
      },
    },
    displayOptions: props.displayOptions,
  });

  instance.value = embed;
  status.value = EmbedStatuses.INITIALIZING;

  embed.on("paramChanged", (payload) => emit("paramChanged", payload));
  embed.on("executeSqlsTriggered", (payload) =>
    emit("executeSqlsTriggered", payload)
  );

  try {
    await embed.init();
    status.value = embed.status;
    emit("ready");
  } catch (err: unknown) {
    setError(err);
    status.value = EmbedStatuses.DESTROYED;
  }
});

onUnmounted(() => {
  if (instance.value) {
    instance.value.destroy();
    instance.value = null;
  }
  status.value = EmbedStatuses.DESTROYED;
});

const reload = async (): Promise<boolean> => {
  if (!instance.value) return false;
  try {
    await instance.value.reload();
    status.value = instance.value.status;
    return true;
  } catch (err: unknown) {
    setError(err);
    return false;
  }
};

defineExpose({
  reload,
  status,
});
</script>

<template>
  <div ref="containerRef" class="codatum-embed-vue-container" />
</template>

<style scoped>
.codatum-embed-vue-container {
  display: contents;
}
</style>

// packages/embed-react/src/Embed.tsx
import type {
  DisplayOptions,
  EmbedInstance,
  EmbedStatus,
  ExecuteSqlsTriggeredMessage,
  IframeOptions,
  ParamChangedMessage,
  TokenOptions,
  TokenProviderContext,
  TokenProviderResult,
} from "@codatum/embed";
import { createEmbed, EmbedError, EmbedErrorCodes, EmbedStatuses } from "@codatum/embed";
import { forwardRef, useCallback, useEffect, useImperativeHandle, useRef, useState } from "react";

const toEmbedError = (err: unknown): EmbedError =>
  err instanceof EmbedError
    ? err
    : new EmbedError(
        EmbedErrorCodes.TOKEN_PROVIDER_FAILED,
        err instanceof Error ? err.message : String(err),
        { cause: err },
      );

export interface EmbedReactProps {
  embedUrl: string;
  tokenProvider: (context: TokenProviderContext) => Promise<TokenProviderResult>;
  iframeOptions?: IframeOptions;
  tokenOptions?: TokenOptions;
  displayOptions?: DisplayOptions;
  onReady?: () => void;
  onParamChanged?: (payload: ParamChangedMessage) => void;
  onExecuteSqlsTriggered?: (payload: ExecuteSqlsTriggeredMessage) => void;
  onError?: (err: EmbedError) => void;
}

export interface EmbedReactRef {
  reload: () => Promise<boolean>;
  status: EmbedStatus;
}

export const Embed = forwardRef<EmbedReactRef, EmbedReactProps>(function Embed(
  {
    embedUrl,
    tokenProvider,
    iframeOptions,
    tokenOptions,
    displayOptions,
    onReady,
    onParamChanged,
    onExecuteSqlsTriggered,
    onError,
  },
  ref,
) {
  const containerRef = useRef<HTMLDivElement>(null);
  const instanceRef = useRef<EmbedInstance | null>(null);
  const [status, setStatus] = useState<EmbedStatus>(EmbedStatuses.CREATED);

  const callbacksRef = useRef({
    onParamChanged,
    onExecuteSqlsTriggered,
    onReady,
    onError,
  });
  callbacksRef.current = {
    onParamChanged,
    onExecuteSqlsTriggered,
    onReady,
    onError,
  };

  const setError = useCallback((err: unknown) => {
    const embedError = toEmbedError(err);
    callbacksRef.current.onError?.(embedError);
  }, []);

  // biome-ignore lint/correctness/useExhaustiveDependencies: intentional mount-only init, same as embed-vue
  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;

    const embed = createEmbed({
      container: el,
      embedUrl,
      tokenProvider,
      iframeOptions,
      tokenOptions: {
        ...tokenOptions,
        onRefreshError: (err: EmbedError) => {
          tokenOptions?.onRefreshError?.(err);
          setError(err);
        },
      },
      displayOptions,
    });

    instanceRef.current = embed;
    setStatus(EmbedStatuses.INITIALIZING);

    embed.on("paramChanged", (payload) => callbacksRef.current.onParamChanged?.(payload));
    embed.on("executeSqlsTriggered", (payload) =>
      callbacksRef.current.onExecuteSqlsTriggered?.(payload),
    );

    let cancelled = false;
    embed
      .init()
      .then(() => {
        if (!cancelled && instanceRef.current === embed) {
          setStatus(embed.status);
          callbacksRef.current.onReady?.();
        }
      })
      .catch((err: unknown) => {
        if (!cancelled) {
          setError(err);
          setStatus(EmbedStatuses.DESTROYED);
        }
      });

    return () => {
      cancelled = true;
      if (instanceRef.current === embed) {
        embed.destroy();
        instanceRef.current = null;
      }
      setStatus(EmbedStatuses.DESTROYED);
    };
  }, []);

  useImperativeHandle(
    ref,
    () => ({
      get status() {
        return status;
      },
      reload: async (): Promise<boolean> => {
        const inst = instanceRef.current;
        if (!inst) return false;
        try {
          await inst.reload();
          setStatus(inst.status);
          return true;
        } catch (err: unknown) {
          setError(err);
          return false;
        }
      },
    }),
    [status, setError],
  );

  return <div ref={containerRef} className="codatum-embed-react-container" />;
});
