// examples/vue/src/scenarios/Scenario2.vue
<script setup lang="ts">
import {
  EmbedVue,
  createParamMapper,
  RESET_TO_DEFAULT,
  type EmbedError,
  type EncodedParam,
  type DefineDecodedParams,
  type DefineParamMapper,
  type TokenProviderContext,
} from "@codatum/embed-vue";
import { onMounted, ref, computed } from "vue";

const API_URL = "http://localhost:3100/scenario2";
type Config = {
  embedUrl: string;
  paramMapping: { [key: string]: string };
  userId: string;
  storeIds: string[];
};

const embedUrl = ref<string | null>(null);
const userId = ref<string | null>(null);
const storeIds = ref<string[]>([]);
const statusMessage = ref("Loading config…");
const statusError = ref(false);

const paramDefs = {
  store_id: { datatype: "STRING" },
  date_range: { datatype: "[DATE, DATE]" },
  product_category: { datatype: "STRING[]" },
} as const;

type ParamValues = DefineDecodedParams<typeof paramDefs>;
type ParamMapper = DefineParamMapper<typeof paramDefs>;

const paramMapper = ref<ParamMapper | null>(null);
const paramValues = ref<ParamValues>({
  store_id: undefined,
  date_range: RESET_TO_DEFAULT,
  product_category: [],
});

onMounted(async () => {
  try {
    const configRes = await fetch(`${API_URL}/config`);
    if (!configRes.ok) throw new Error(`config failed: ${configRes.status}`);
    const config: Config = await configRes.json();
    embedUrl.value = config.embedUrl;
    userId.value = config.userId;
    storeIds.value = config.storeIds;
    paramMapper.value = createParamMapper(
      config.paramMapping,
      paramDefs
    ) as ParamMapper;
    statusMessage.value = "Initializing…";
  } catch (err) {
    statusMessage.value =
      "Failed to fetch config. Ensure the server is running at localhost:3100.";
    statusError.value = true;
    console.error(err);
  }
});

const onReady = () => {
  statusMessage.value = "Ready";
  statusError.value = false;
};

const cachedToken = ref<string | null>(null);

const tokenProvider = async (ctx: TokenProviderContext) => {
  // When server-side params are unchanged, the token can be reused.
  // In production: validate expiry and do not reuse across different users.
  let token = cachedToken.value;
  if (!token) {
    const res = await fetch(`${API_URL}/token`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        tokenUserId: userId.value,
      }),
    });
    if (!res.ok) {
      const data = (await res.json()) as { message?: string };
      throw new Error(data.message ?? "Token issuance failed");
    }
    const data = (await res.json()) as { token: string };
    token = data.token;
    cachedToken.value = token;
  }
  let clientParams: EncodedParam[] = [];
  try {
    clientParams =
      paramMapper.value?.encode(paramValues.value, {
        only: ["store_id", "date_range", "product_category"],
      }) ?? [];
  } catch (err) {
    // skip retries if params are invalid
    ctx.markNonRetryable();
    throw err;
  }
  return {
    token,
    params: clientParams,
  };
};

const onParamChanged = (ev: { params: EncodedParam[] }) => {
  if (!paramMapper.value) return;
  paramValues.value = paramMapper.value.decode(ev.params);
};

const onEmbedError = (err: EmbedError) => {
  statusMessage.value = err.message;
  statusError.value = true;
};

const embedRef = ref<InstanceType<typeof EmbedVue> | null>(null);
const reloadEmbed = async () => {
  const success = await embedRef.value?.reload();
  if (success) {
    statusMessage.value = "Reloaded";
    statusError.value = false;
  }
};

/** form handlers */
const dateRangeStart = computed({
  get: () => {
    if (paramValues.value.date_range === RESET_TO_DEFAULT) return "";
    return paramValues.value.date_range?.[0] ?? "";
  },
  set: (v: string) => {
    const prev = paramValues.value.date_range ?? ["", ""];
    paramValues.value = {
      ...paramValues.value,
      date_range: [v, prev[1] ?? ""],
    };
  },
});
const dateRangeEnd = computed({
  get: () => {
    if (paramValues.value.date_range === RESET_TO_DEFAULT) return "";
    return paramValues.value.date_range?.[1] ?? "";
  },
  set: (v: string) => {
    const prev = paramValues.value.date_range ?? ["", ""];
    paramValues.value = {
      ...paramValues.value,
      date_range: [prev[0] ?? "", v],
    };
  },
});

const productCategoryArray = computed(
  () => paramValues.value.product_category ?? []
);

const updateProductCategory = (index: number, value: string): void => {
  const arr = [...(paramValues.value.product_category ?? [])];
  arr[index] = value;
  paramValues.value = {
    ...paramValues.value,
    product_category: arr,
  };
};

const addProductCategory = (): void => {
  paramValues.value = {
    ...paramValues.value,
    product_category: [...(paramValues.value.product_category ?? []), ""],
  };
};

const removeProductCategory = (index: number): void => {
  const arr = [...(paramValues.value.product_category ?? [])];
  arr.splice(index, 1);
  paramValues.value = {
    ...paramValues.value,
    product_category: arr,
  };
};
</script>

<template>
  <div class="border rounded p-3 bg-light mb-3">
    <h2 class="h6 mb-3">Parameters</h2>
    <div class="mb-2">
      <label for="store_id" class="form-label small mb-1">Store Id</label>
      <select
        id="store_id"
        v-model="paramValues.store_id"
        class="form-control form-control-sm"
      >
        <option v-for="storeId in storeIds" :key="storeId" :value="storeId">
          {{ storeId }}
        </option>
      </select>
    </div>
    <div class="mb-2">
      <label for="date_range" class="form-label small mb-1">Date Range</label>
      <div class="row g-2">
        <div class="col">
          <input
            id="date_range-start"
            v-model="dateRangeStart"
            type="text"
            class="form-control form-control-sm"
            placeholder="Start"
          />
        </div>
        <div class="col">
          <input
            id="date_range-end"
            v-model="dateRangeEnd"
            type="text"
            class="form-control form-control-sm"
            placeholder="End"
          />
        </div>
      </div>
    </div>
    <div class="mb-3">
      <label class="form-label small mb-1">Product Category</label>
      <div
        v-for="(item, index) in productCategoryArray"
        :key="index"
        class="input-group input-group-sm mb-2"
      >
        <input
          :value="item"
          type="text"
          class="form-control form-control-sm"
          placeholder="Category"
          @input="
            updateProductCategory(
              index,
              ($event.target as HTMLInputElement).value
            )
          "
        />
        <button
          type="button"
          class="btn btn-outline-secondary"
          aria-label="Remove"
          @click="removeProductCategory(index)"
        >
          ×
        </button>
      </div>
      <button
        type="button"
        class="btn btn-outline-secondary btn-sm"
        @click="addProductCategory"
      >
        + Add category
      </button>
    </div>
    <div class="text-end">
      <button
        type="button"
        @click="reloadEmbed"
        class="btn btn-outline-secondary"
      >
        Reload
      </button>
    </div>
  </div>
  <div
    class="alert py-2 mb-3"
    :class="statusError ? 'alert-danger' : 'alert-success'"
  >
    {{ statusMessage }}
  </div>
  <div v-if="embedUrl" class="border bg-white">
    <EmbedVue
      ref="embedRef"
      :embedUrl="embedUrl"
      :tokenProvider="tokenProvider"
      :iframeOptions="{
        theme: 'LIGHT',
        locale: 'en',
        className: 'vue-example-iframe',
        style: { height: '600px' },
      }"
      :displayOptions="{ hideParamsForm: true }"
      :devOptions="{ debug: true, disableValidateUrl: true }"
      @ready="onReady"
      @paramChanged="onParamChanged"
      @executeSqlsTriggered="onParamChanged"
      @error="onEmbedError"
    />
  </div>
</template>

// examples/react/src/scenarios/Scenario2.tsx
import {
  createParamMapper,
  type DefineDecodedParams,
  type DefineParamMapper,
  type EmbedError,
  EmbedReact,
  type EmbedReactRef,
  type EncodedParam,
  RESET_TO_DEFAULT,
  type TokenProviderContext,
} from "@codatum/embed-react";
import { useCallback, useEffect, useRef, useState } from "react";

const API_URL = "http://localhost:3100/scenario2";
type Config = {
  embedUrl: string;
  paramMapping: { [key: string]: string };
  userId: string;
  storeIds: string[];
};

const paramDefs = {
  store_id: { datatype: "STRING" },
  date_range: { datatype: "[DATE, DATE]" },
  product_category: { datatype: "STRING[]" },
} as const;

type ParamValues = DefineDecodedParams<typeof paramDefs>;
type ParamMapper = DefineParamMapper<typeof paramDefs>;

export default function Scenario2() {
  const [embedUrl, setEmbedUrl] = useState<string | null>(null);
  const [userId, setUserId] = useState<string | null>(null);
  const [storeIds, setStoreIds] = useState<string[]>([]);
  const [statusMessage, setStatusMessage] = useState("Loading config…");
  const [statusError, setStatusError] = useState(false);
  const [paramMapper, setParamMapper] = useState<ParamMapper | null>(null);
  const [paramValues, setParamValues] = useState<ParamValues>({
    store_id: undefined,
    date_range: RESET_TO_DEFAULT,
    product_category: [],
  });
  const cachedTokenRef = useRef<string | null>(null);
  const embedRef = useRef<EmbedReactRef>(null);
  const paramValuesRef = useRef(paramValues);
  const paramMapperRef = useRef(paramMapper);
  const userIdRef = useRef(userId);
  paramValuesRef.current = paramValues;
  paramMapperRef.current = paramMapper;
  userIdRef.current = userId;

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const configRes = await fetch(`${API_URL}/config`);
        if (!configRes.ok) throw new Error(`config failed: ${configRes.status}`);
        const config: Config = await configRes.json();
        if (cancelled) return;
        setEmbedUrl(config.embedUrl);
        setUserId(config.userId);
        setStoreIds(config.storeIds);
        setParamMapper(createParamMapper(config.paramMapping, paramDefs) as ParamMapper);
        setStatusMessage("Initializing…");
      } catch (err) {
        if (!cancelled) {
          setStatusMessage(
            "Failed to fetch config. Ensure the server is running at localhost:3100.",
          );
          setStatusError(true);
          console.error(err);
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  const onReady = useCallback(() => {
    setStatusMessage("Ready");
    setStatusError(false);
  }, []);

  const tokenProvider = useCallback(async (ctx: TokenProviderContext) => {
    let token = cachedTokenRef.current;
    if (!token) {
      const res = await fetch(`${API_URL}/token`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          tokenUserId: userIdRef.current,
        }),
      });
      if (!res.ok) {
        const data = (await res.json()) as { message?: string };
        throw new Error(data.message ?? "Token issuance failed");
      }
      const data = (await res.json()) as { token: string };
      token = data.token;
      cachedTokenRef.current = token;
    }
    let clientParams: EncodedParam[] = [];
    try {
      clientParams =
        paramMapperRef.current?.encode(paramValuesRef.current, {
          only: ["store_id", "date_range", "product_category"],
        }) ?? [];
    } catch (err) {
      ctx.markNonRetryable();
      throw err;
    }
    return {
      token,
      params: clientParams,
    };
  }, []);

  const onParamChanged = useCallback(
    (ev: { params: EncodedParam[] }) => {
      if (!paramMapper) return;
      setParamValues(paramMapper.decode(ev.params));
    },
    [paramMapper],
  );

  const onEmbedError = useCallback((err: EmbedError) => {
    setStatusMessage(err.message);
    setStatusError(true);
  }, []);

  const reloadEmbed = useCallback(async () => {
    const success = await embedRef.current?.reload();
    if (success) {
      setStatusMessage("Reloaded");
      setStatusError(false);
    }
  }, []);

  const dateRangeStart =
    paramValues.date_range === RESET_TO_DEFAULT ? "" : (paramValues.date_range?.[0] ?? "");
  const dateRangeEnd =
    paramValues.date_range === RESET_TO_DEFAULT ? "" : (paramValues.date_range?.[1] ?? "");
  const productCategoryArray =
    paramValues.product_category === RESET_TO_DEFAULT ? [] : (paramValues.product_category ?? []);

  const setDateRangeStart = (v: string) => {
    const prev = paramValues.date_range ?? ["", ""];
    setParamValues({
      ...paramValues,
      date_range: [v, prev[1] ?? ""],
    });
  };
  const setDateRangeEnd = (v: string) => {
    const prev = paramValues.date_range ?? ["", ""];
    setParamValues({
      ...paramValues,
      date_range: [prev[0] ?? "", v],
    });
  };
  const updateProductCategory = (index: number, value: string) => {
    const arr = [...(paramValues.product_category ?? [])];
    arr[index] = value;
    setParamValues({
      ...paramValues,
      product_category: arr,
    });
  };
  const addProductCategory = () => {
    setParamValues({
      ...paramValues,
      product_category: [...(paramValues.product_category ?? []), ""],
    });
  };
  const removeProductCategory = (index: number) => {
    const arr = [...(paramValues.product_category ?? [])];
    arr.splice(index, 1);
    setParamValues({
      ...paramValues,
      product_category: arr,
    });
  };

  return (
    <>
      <div className="border rounded p-3 bg-light mb-3">
        <h2 className="h6 mb-3">Parameters</h2>
        <div className="mb-2">
          <label htmlFor="store_id" className="form-label small mb-1">
            Store Id
          </label>
          <select
            id="store_id"
            value={paramValues.store_id ?? ""}
            onChange={(e) =>
              setParamValues({
                ...paramValues,
                store_id: e.target.value || undefined,
              })
            }
            className="form-control form-control-sm"
          >
            {storeIds.map((storeId) => (
              <option key={storeId} value={storeId}>
                {storeId}
              </option>
            ))}
          </select>
        </div>
        <div className="mb-2">
          <label htmlFor="date_range" className="form-label small mb-1">
            Date Range
          </label>
          <div className="row g-2">
            <div className="col">
              <input
                id="date_range-start"
                value={dateRangeStart}
                onChange={(e) => setDateRangeStart(e.target.value)}
                type="text"
                className="form-control form-control-sm"
                placeholder="Start"
              />
            </div>
            <div className="col">
              <input
                id="date_range-end"
                value={dateRangeEnd}
                onChange={(e) => setDateRangeEnd(e.target.value)}
                type="text"
                className="form-control form-control-sm"
                placeholder="End"
              />
            </div>
          </div>
        </div>
        <fieldset className="mb-3 border-0 p-0">
          <legend className="form-label small mb-1">Product Category</legend>
          {productCategoryArray.map((item, index) => (
            <div key={index} className="input-group input-group-sm mb-2">
              <input
                value={item}
                type="text"
                className="form-control form-control-sm"
                placeholder="Category"
                onChange={(e) => updateProductCategory(index, e.target.value)}
              />
              <button
                type="button"
                className="btn btn-outline-secondary"
                aria-label="Remove"
                onClick={() => removeProductCategory(index)}
              >
                ×
              </button>
            </div>
          ))}
          <button
            type="button"
            className="btn btn-outline-secondary btn-sm"
            onClick={addProductCategory}
          >
            + Add category
          </button>
        </fieldset>
        <div className="text-end">
          <button type="button" onClick={reloadEmbed} className="btn btn-outline-secondary">
            Reload
          </button>
        </div>
      </div>
      <div className={`alert py-2 mb-3 ${statusError ? "alert-danger" : "alert-success"}`}>
        {statusMessage}
      </div>
      {embedUrl && (
        <div className="border bg-white">
          <EmbedReact
            ref={embedRef}
            embedUrl={embedUrl}
            tokenProvider={tokenProvider}
            iframeOptions={{
              theme: "LIGHT",
              locale: "en",
              className: "react-example-iframe",
              style: { height: "600px" },
            }}
            displayOptions={{ hideParamsForm: true }}
            devOptions={{ debug: true, disableValidateUrl: true }}
            onReady={onReady}
            onParamChanged={onParamChanged}
            onExecuteSqlsTriggered={onParamChanged}
            onError={onEmbedError}
          />
        </div>
      )}
    </>
  );
}
